# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_test',
                'doc_host': 'https://cfowler1woolworths.github.io',
                'git_url': 'https://github.com/cfowler1woolworths/nbdev_test',
                'lib_path': 'nbdev_test'},
  'syms': {'nbdev_test.core': {'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py')}}}
